apiVersion: v1
data:
  app.conf: |
    server {
      # this is from configmap volume
        listen 80;
        index index.php index.html login/login.php;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /usr/share/nginx/html/piktorya;
      # location / {
      #     try_files $uri $uri/ =404;
      # }
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass app:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location / {
            try_files $uri $uri/ login/login.php?$query_string;
            gzip_static on;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-07-02T19:19:59Z"
  name: appconf
  namespace: default
  resourceVersion: "106708"
  selfLink: /api/v1/namespaces/default/configmaps/appconf
  uid: 625d8ac0-9cfe-11e9-9201-e2b1398def36
