apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: app
status:
  loadBalancer: {}
